### ISSUE TITLE
Error: 'The normalize vertical-rhythm module only supports px inputs. The typey library is better.'

### ISSUE THREAD

**Issue by Garfield550** [JohnAlbin/normalize-scss#111]
``` Text
ERROR in ./src/sass/mvxtheme.scss
Module build failed: ModuleBuildError: Module build failed:
    @error "The normalize vertical-rhythm module only supports px inputs. The typey library is better.";
   ^
      The normalize vertical-rhythm module only supports px inputs. The typey library is better.
      in /mnt/c/Users/garfi/Documents/GitHub/.../node_modules/normalize-scss/sass/normalize/_vertical-rhythm.scss (line 10, column 5)
    at runLoaders (/mnt/c/Users/garfi/Documents/GitHub/.../node_modules/webpack/lib/NormalModule.js:194:19)
    at /mnt/c/Users/garfi/Documents/GitHub/.../node_modules/loader-runner/lib/LoaderRunner.js:364:11
    at /mnt/c/Users/garfi/Documents/GitHub/.../node_modules/loader-runner/lib/LoaderRunner.js:230:18
    at context.callback (/mnt/c/Users/garfi/Documents/GitHub/.../node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at Object.asyncSassJobQueue.push [as callback] (/mnt/c/Users/garfi/Documents/GitHub/.../node_modules/sass-loader/lib/loader.js:55:13)
    at Object.<anonymous> (/mnt/c/Users/garfi/Documents/GitHub/.../node_modules/async/dist/async.js:2244:31)
    at Object.callback (/mnt/c/Users/garfi/Documents/GitHub/.../node_modules/async/dist/async.js:906:16)
    at options.error (/mnt/c/Users/garfi/Documents/GitHub/.../node_modules/node-sass/lib/index.js:294:32)
 @ ./src/index.js 3:0-26
```

mvxtheme.scss

``` SCSS
@import '~normalize-scss/sass/_normalize.scss';
@include normalize();
```

**Comment by garrettw** [comment]
So are you using an input value in px units?

**Comment by Garfield550** [comment]
@garrettw I use default variables... I just use normalize() mixin

**Comment by wsfuller** [comment]
Has there been any resolution to this? I'm having the same issue and used the Typey library which didn't work. 

The only solution that has worked is just declaring my `rem` units after `@include normalize()`

**Comment by JohnAlbin** [comment]
You would only be getting that error if you are setting a value to one of these variables: https://github.com/JohnAlbin/normalize-scss/blob/master/sass/normalize/_variables.scss

Or if another library is also using those same variable names with unexpected values.
