### ISSUE TITLE
SyntaxError: Unexpected token ILLEGAL when required from GruntFile

### ISSUE THREAD

**Issue by sentience** [JohnAlbin/normalize-scss#48]
I am using Grunt (with grunt-sass) to build my site’s CSS. I’ve used NPM to install normalize-scss, but when I `require('normalize-scss')` in my GruntFile.js, I get a `SyntaxError`:

```
Loading "GruntFile.js" tasks...ERROR
>> SyntaxError: Unexpected token ILLEGAL
>>     at exports.runInThisContext (vm.js:53:16)
>>     at Module._compile (module.js:404:25)
>>     at Object.Module._extensions..js (module.js:432:10)
>>     at Module.load (module.js:356:32)
>>     at Function.Module._load (module.js:311:12)
>>     at Module.require (module.js:366:17)
>>     at require (module.js:385:17)
>>     at Object.module.exports (/Users/kyank/code/impromelbourne.com.au/GruntFile.js:26:11)
>>     at loadTask (/Users/kyank/code/impromelbourne.com.au/node_modules/grunt/lib/grunt/task.js:325:10)
>>     at Task.task.init (/Users/kyank/code/impromelbourne.com.au/node_modules/grunt/lib/grunt/task.js:437:5)
```

NodeJS v5.0.0 on OS X 10.11.2.

Any idea what I might be doing wrong?

**Comment by sentience** [comment]
OK, so what I was doing wrong was trying to require a CSS file from a JS file. ;)

This worked for me in my GruntFile.js:

```javascript
    sass: {
      options: {
        includePaths: require('node-neat').with(
          require('path').dirname(require.resolve('normalize-scss')),
          require('path').dirname(require.resolve('support-for'))
        ),
```

**Comment by JohnAlbin** [comment]
@sentience Ooh. That's a pretty good way to get the proper importPaths. I like it!

Related: https://github.com/JohnAlbin/normalize-scss/issues/43#issuecomment-198710520

**Comment by JohnAlbin** [comment]
Will follow up in #58.
